#!/bin/bash
# This is my first script.

for i in {1..15}
do
./JxrEncApp -L 32 -q $i -i test_data1 -h 560 -w 576 -o out.jxr
./JxrDecApp -i out.jxr -o out.tif
./snr out.tif test_data1 576 560 32
ls -l out.jxr  | awk '{print  $5}'
done

echo =====================

for i in {1..15}
do
./JxrEncApp -L 32 -q $i -i test_data2 -h 560 -w 576 -o out.jxr 
./JxrDecApp -i out.jxr -o working
./snr working test_data2 576 560 32
ls -l out.jxr  | awk '{print  $5}'
done

echo =====================

for i in {1..15}
do
./JxrEncApp -L 16 -q $i -i wavefield1_16b -h 560 -w 576 -o out.jxr
./JxrDecApp -i out.jxr -o try.tif
./snr try.tif wavefield1_16b 576 560 16 
ls -l out.jxr  | awk '{print  $5}'
done

echo =====================
for i in {1..15}
do
./JxrEncApp -L 8 -q $i -i wavefield1_8b -h 560 -w 576 -o out.jxr
./JxrDecApp -i out.jxr -o out 
./snr out wavefield1_8b 576 560 8
ls -l out.jxr  | awk '{print  $5}'
done


echo =====================
for i in {1..15}
do
./JxrEncApp -L 32f -q $i -i x1_of -h 241 -w 1025 -o out.jxr
./JxrDecApp -i out.jxr -o t.raw -F
#./scaleback out.tif out.float 1025 241 2.922378784770679e-09
./mse_ori t.raw x1_of 1025 241
ls -l out.jxr  | awk '{print  $5}'
done
