#!/bin/bash
# This is my first script.
rm out.txt

for i in {1..9}
do
for j in {0..9}
do
 { time -p ./JxrEncApp -L 16 -R $i.0$j -i wavefield1_16b -h 560 -w 576 -o out.jxr; } 2>> out.txt
#./JxrEncApp -L 16 -R $i.0$j -i wavefield1_16b -h 560 -w 576 -o out.jxr >> out.txt
done
for j in {10..99}
do
 { time -p ./JxrEncApp -L 16 -R $i.$j -i wavefield1_16b -h 560 -w 576 -o out.jxr; } 2>> out.txt
#./JxrEncApp -L 16 -R $i.$j -i wavefield1_16b -h 560 -w 576 -o out.jxr >> out.txt
done
done

for i in {10..20}
do
for j in {0..9}
do
 { time -p ./JxrEncApp -L 16 -R $i.$j -i wavefield1_16b -h 560 -w 576 -o out.jxr; } 2>> out.txt
#./JxrEncApp -L 16 -R $i.$j -i wavefield1_16b -h 560 -w 576 -o out.jxr >> out.txt
done
done